theme: minima
title: Zhou Fang's homepage
header_pages:
  - CV.md
  - Research.md
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/jekyll/jekyll" }
    - { platform: linkedin, user_url: "https://twitter.com/jekyllrb" }
